apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: platform-opensearch
data:
  opensearch.yml: |
    cluster.name: soc-platform
    node.name: opensearch-0
    network.host: 0.0.0.0

    discovery.type: single-node

    # Snapshots repo allowlist (required for filesystem snapshot repos)
    path.repo: ["/usr/share/opensearch/backup"]

    # ---- Security plugin (TLS) ----
    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.pemcert_filepath: certs/node.pem
    plugins.security.ssl.transport.pemkey_filepath: certs/node.key
    plugins.security.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false

    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: certs/node.pem
    plugins.security.ssl.http.pemkey_filepath: certs/node.key
    plugins.security.ssl.http.pemtrustedcas_filepath: certs/root-ca.pem

    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - "CN=admin"

    # If you use tenants (you do)
    plugins.security.multitenancy.enabled: true
    plugins.security.multitenancy.tenants.enable_private: true
    plugins.security.multitenancy.tenants.enable_global: true

    # Helpful defaults
    action.auto_create_index: true