apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.11.1
          resources:
            requests:
             memory: "512Mi"
             cpu: "250m"
            limits:
            memory: "1Gi"
            cpu: "500m"
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - port: 9200
      targetPort: 9200
