apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - resources:
  - serviceaccount.yaml
  - service.yaml
  - statefulset.yaml
  - vector-config.yaml

labels:
  - pairs:
      env: dev
      app.kubernetes.io/part-of: soc-platform
