apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-opensearch

resources:
  - ../../base

configMapGenerator:
  - name: opensearch-config
    behavior: replace
    files:
      - opensearch.yml

patchesStrategicMerge:
  - opensearch-sts-security-init.patch.yaml
