apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-filebeat-config
  namespace: platform-wazuh
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/ossec/logs/alerts/alerts.json
        json.keys_under_root: true
        json.add_error_key: true
        ignore_older: 0
        close_inactive: 1m

    processors:
      - add_fields:
          target: ""
          fields:
            event_source: wazuh

    setup.template.enabled: false
    setup.ilm.enabled: false

    output.elasticsearch:
      hosts: ["http://opensearch.platform-opensearch.svc.cluster.local:9200"]
      index: "wazuh-alerts-%{+yyyy.MM.dd}"
