apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-filebeat-config
  namespace: platform-wazuh
data:
  filebeat.yml: |
    filebeat.inputs: []
    logging.level: warning

    queue.mem:
      events: 128
      flush.min_events: 64
      flush.timeout: 1s

    output.elasticsearch:
      hosts: ["http://opensearch.platform-opensearch.svc.cluster.local:9200"]
