apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-wazuh

commonLabels:
  app.kubernetes.io/part-of: soc-platform
  app.kubernetes.io/instance: soc-platform

resources:
  - serviceaccount.yaml
  - service.yaml
  - statefulset.yaml
  - vector-config.yaml
