apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
  labels:
    app: wazuh-manager
spec:
  serviceName: wazuh-manager
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
        - name: init-ossec
          image: busybox:1.36
          command:
            - sh
            - -lc
            - |
              mkdir -p /var/ossec/logs/alerts
              touch /var/ossec/logs/alerts/alerts.json
              chmod -R 0775 /var/ossec || true
          volumeMounts:
            - name: wazuh-data
              mountPath: /var/ossec

      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.14.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: agent-udp
              containerPort: 1514
              protocol: UDP
            - name: agent-tcp
              containerPort: 1514
              protocol: TCP
            - name: enrollment
              containerPort: 1515
              protocol: TCP
            - name: api
              containerPort: 55000
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "1200Mi"
            limits:
              cpu: "1000m"
              memory: "2500Mi"
          volumeMounts:
            - name: wazuh-data
              mountPath: /var/ossec
          readinessProbe:
            exec:
              command: ["/bin/sh","-lc","pgrep -f wazuh-analysisd >/dev/null"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            exec:
              command: ["/bin/sh","-lc","pgrep -f wazuh-analysisd >/dev/null"]
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6

        - name: vector
          image: timberio/vector:0.53.0-alpine
          imagePullPolicy: IfNotPresent
          args: ["--config", "/etc/vector/vector.yaml"]
          resources:
            requests:
              cpu: "25m"
              memory: "96Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - name: vector-health
              containerPort: 8686
          volumeMounts:
            - name: wazuh-data
              mountPath: /var/ossec
              readOnly: true
            - name: vector-config
              mountPath: /etc/vector
            - name: vector-data
              mountPath: /tmp/vector
          readinessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: vector-config
          configMap:
            name: wazuh-vector-config
        - name: vector-data
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: wazuh-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
