apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.yaml: |
    api:
      enabled: true
      address: 0.0.0.0:8686

    sources:
      wazuh_alerts_json:
        type: file
        include:
          - /var/ossec/logs/alerts/alerts.json
        read_from: beginning

    sinks:
      opensearch_wazuh_alerts:
        type: elasticsearch
        inputs:
          - wazuh_alerts_json
        endpoints:
          - "https://opensearch.platform-opensearch.svc.cluster.local:9200"
        bulk:
          index: "wazuh-alerts-%Y.%m.%d"
        tls:
          ca_file: /etc/vector/certs/root-ca.pem
          verify_certificate: true
          verify_hostname: true
