apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soc-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JarrandyR/soc-platform
    targetRevision: main
    path: gitops/clusters/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
