apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../snapshots/base

patches:
  - path: patch-opensearch-sts.yaml
  - path: patch-opensearch-configmap.yaml
  - path: patch-opensearch-service.yaml