apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify-webhook
  template:
    metadata:
      labels:
        app: notify-webhook
    spec:
      containers:
        - name: webhook
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=SOC Notify OK"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: notify-webhook
spec:
  selector:
    app: notify-webhook
  ports:
    - port: 9000
      targetPort: 5678
